# Generated by Django 5.1.2 on 2024-10-16 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trajeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField()),
                ('tempo_do_trajeto', models.TimeField()),
                ('endereco_comeco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endereco_trajeto_start', to='core.endereco')),
                ('endereco_final', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endereco_trajeto_final', to='core.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('distancia_realizada', models.FloatField()),
                ('posicao', models.IntegerField()),
                ('pace', models.TimeField()),
                ('data', models.DateTimeField()),
                ('trajeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trajeto_corrida', to='core.trajeto')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pace_realizado', models.TimeField()),
                ('distancia', models.FloatField()),
                ('data', models.DateTimeField()),
                ('trajeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trajeto_treino', to='core.trajeto')),
            ],
        ),
    ]
